package storage

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type migration struct {
	version    int64
	statements []string
}

const singleActiveBatchIndexName = "batches_single_active_idx"

var migrations = []migration{
	{
		version: 1,
		statements: []string{
			`CREATE TABLE IF NOT EXISTS settings (
				key text PRIMARY KEY,
				value jsonb NOT NULL,
				updated_at timestamptz NOT NULL DEFAULT now()
			)`,
			`CREATE TABLE IF NOT EXISTS batches (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				status text NOT NULL DEFAULT 'pending',
				service_code text NOT NULL,
				service_name text NOT NULL DEFAULT '',
				country_code text NOT NULL,
				country_name text NOT NULL DEFAULT '',
				max_price_amount numeric(18,6) NOT NULL,
				currency text NOT NULL DEFAULT '',
				target_pin_enc bytea NOT NULL DEFAULT ''::bytea,
				config jsonb NOT NULL DEFAULT '{}'::jsonb,
				next_purchase_at timestamptz NOT NULL DEFAULT now(),
				quantity integer NOT NULL CHECK (quantity > 0),
				purchased_count integer NOT NULL DEFAULT 0 CHECK (purchased_count >= 0),
				fulfilled_count integer NOT NULL DEFAULT 0 CHECK (fulfilled_count >= 0),
				inflight_count integer NOT NULL DEFAULT 0 CHECK (inflight_count >= 0),
				failure_reason text NOT NULL DEFAULT '',
				created_at timestamptz NOT NULL DEFAULT now(),
				updated_at timestamptz NOT NULL DEFAULT now(),
				started_at timestamptz,
				finished_at timestamptz,
				CHECK (fulfilled_count <= quantity),
				CHECK (fulfilled_count + inflight_count <= quantity)
			)`,
			`CREATE INDEX IF NOT EXISTS batches_status_created_idx ON batches (status, created_at DESC)`,
			`CREATE TABLE IF NOT EXISTS accounts (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				phone_number text NOT NULL,
				phone_fingerprint char(64) NOT NULL UNIQUE,
				status text NOT NULL,
				balance_rp numeric(24,6),
				credentials_enc bytea NOT NULL DEFAULT ''::bytea,
				target_pin_enc bytea NOT NULL DEFAULT ''::bytea,
				token_state jsonb NOT NULL DEFAULT '{}'::jsonb,
				device_state jsonb NOT NULL DEFAULT '{}'::jsonb,
				metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
				last_login_at timestamptz,
				created_at timestamptz NOT NULL DEFAULT now(),
				updated_at timestamptz NOT NULL DEFAULT now()
			)`,
			`CREATE INDEX IF NOT EXISTS accounts_status_updated_idx ON accounts (status, updated_at DESC)`,
			`CREATE TABLE IF NOT EXISTS activations (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				batch_id bigint NOT NULL REFERENCES batches(id) ON DELETE RESTRICT,
				account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
				provider text NOT NULL,
				provider_activation_id text NOT NULL,
				phone_number text NOT NULL,
				phone_fingerprint char(64) NOT NULL,
				service_code text NOT NULL,
				country_code text NOT NULL,
				operator text NOT NULL DEFAULT '',
				purchase_price_amount numeric(18,6) NOT NULL,
				currency text NOT NULL DEFAULT '',
				status text NOT NULL DEFAULT 'purchased',
				failure_reason text NOT NULL DEFAULT '',
				balance_rp numeric(24,6),
				balance_checked_at timestamptz,
				ever_fulfilled boolean NOT NULL DEFAULT false,
				slot_reserved boolean NOT NULL DEFAULT false,
				sms_cycle integer NOT NULL DEFAULT 0 CHECK (sms_cycle >= 0),
				next_run_at timestamptz NOT NULL DEFAULT now(),
				lease_owner text NOT NULL DEFAULT '',
				lease_until timestamptz,
				lease_version bigint NOT NULL DEFAULT 0 CHECK (lease_version >= 0),
				control_action text NOT NULL DEFAULT '',
				provider_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
				provider_expires_at timestamptz,
				last_polled_at timestamptz,
				hidden_at timestamptz,
				created_at timestamptz NOT NULL DEFAULT now(),
				updated_at timestamptz NOT NULL DEFAULT now(),
				finished_at timestamptz,
				UNIQUE (provider, provider_activation_id)
			)`,
			`CREATE INDEX IF NOT EXISTS activations_batch_created_idx ON activations (batch_id, created_at DESC)`,
			`CREATE INDEX IF NOT EXISTS activations_visible_idx ON activations (created_at DESC) WHERE hidden_at IS NULL`,
			`CREATE INDEX IF NOT EXISTS activations_runnable_idx ON activations (next_run_at, lease_until) WHERE finished_at IS NULL`,
			`CREATE INDEX IF NOT EXISTS activations_phone_idx ON activations (phone_fingerprint)`,
			`CREATE TABLE IF NOT EXISTS phone_history (
				phone_fingerprint char(64) PRIMARY KEY,
				phone_number text NOT NULL,
				first_activation_id bigint NOT NULL REFERENCES activations(id) ON DELETE RESTRICT,
				last_activation_id bigint NOT NULL REFERENCES activations(id) ON DELETE RESTRICT,
				times_seen integer NOT NULL DEFAULT 1 CHECK (times_seen > 0),
				first_seen_at timestamptz NOT NULL DEFAULT now(),
				last_seen_at timestamptz NOT NULL DEFAULT now()
			)`,
			`CREATE INDEX IF NOT EXISTS phone_history_last_seen_idx ON phone_history (last_seen_at DESC)`,
			`CREATE TABLE IF NOT EXISTS verification_codes (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				activation_id bigint NOT NULL REFERENCES activations(id) ON DELETE RESTRICT,
				cycle_no integer NOT NULL CHECK (cycle_no >= 0),
				phase text NOT NULL,
				ordinal integer NOT NULL CHECK (ordinal >= 0),
				code text NOT NULL,
				provider_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
				provider_received_at timestamptz,
				created_at timestamptz NOT NULL DEFAULT now(),
				UNIQUE (activation_id, cycle_no)
			)`,
			`CREATE INDEX IF NOT EXISTS verification_codes_activation_idx ON verification_codes (activation_id, cycle_no, id)`,
			`CREATE UNIQUE INDEX IF NOT EXISTS verification_codes_subsequent_ordinal_idx
				ON verification_codes (activation_id, ordinal) WHERE phase='subsequent'`,
		},
	},
	{
		version: 2,
		statements: []string{
			`ALTER TABLE batches ADD COLUMN IF NOT EXISTS target_pin_enc bytea NOT NULL DEFAULT ''::bytea`,
			`ALTER TABLE batches ADD COLUMN IF NOT EXISTS next_purchase_at timestamptz NOT NULL DEFAULT now()`,
			`ALTER TABLE activations ADD COLUMN IF NOT EXISTS slot_reserved boolean NOT NULL DEFAULT false`,
			`ALTER TABLE activations ADD COLUMN IF NOT EXISTS lease_version bigint NOT NULL DEFAULT 0`,
		},
	},
	{
		version: 3,
		statements: []string{
			`ALTER TABLE batches ADD COLUMN IF NOT EXISTS purchased_count integer NOT NULL DEFAULT 0 CHECK (purchased_count >= 0)`,
			`UPDATE batches b SET purchased_count=(
				SELECT COUNT(*)::integer FROM activations a WHERE a.batch_id=b.id
			)`,
		},
	},
	{
		version: 4,
		statements: []string{
			// Block concurrent inserts while historical active rows are
			// reconciled and the cross-process uniqueness guard is installed.
			`LOCK TABLE batches IN SHARE ROW EXCLUSIVE MODE`,
			`WITH stale_batches AS (
				SELECT id FROM (
					SELECT id, row_number() OVER (ORDER BY created_at DESC, id DESC) AS active_rank
					FROM batches
					WHERE status IN ('pending','running')
				) ranked
				WHERE active_rank > 1
			)
			UPDATE activations a SET
				control_action='delete',
				hidden_at=COALESCE(a.hidden_at, now()),
				lease_owner='',
				lease_until=NULL,
				lease_version=a.lease_version+1,
				next_run_at=now(),
				updated_at=now()
			FROM stale_batches s
			WHERE a.batch_id=s.id AND a.finished_at IS NULL`,
			`WITH stale_batches AS (
				SELECT id FROM (
					SELECT id, row_number() OVER (ORDER BY created_at DESC, id DESC) AS active_rank
					FROM batches
					WHERE status IN ('pending','running')
				) ranked
				WHERE active_rank > 1
			)
			UPDATE batches b SET
				status='cancelled',
				finished_at=COALESCE(b.finished_at, now()),
				updated_at=now()
			FROM stale_batches s
			WHERE b.id=s.id`,
			`CREATE UNIQUE INDEX IF NOT EXISTS ` + singleActiveBatchIndexName + `
				ON batches ((true)) WHERE status IN ('pending','running')`,
		},
	},
	{
		version: 5,
		statements: []string{
			`ALTER TABLE batches ADD COLUMN IF NOT EXISTS purchase_reserved_count integer NOT NULL DEFAULT 0 CHECK (purchase_reserved_count >= 0)`,
			// New writers explicitly insert protocol version one. Keeping zero as
			// the database default prevents an older binary from starting another
			// unprotected batch after this migration is installed.
			`ALTER TABLE batches ADD COLUMN IF NOT EXISTS purchase_protocol_version integer NOT NULL DEFAULT 0`,
			`CREATE TABLE IF NOT EXISTS batch_purchase_attempts (
				token text PRIMARY KEY CHECK (btrim(token) <> ''),
				batch_id bigint NOT NULL REFERENCES batches(id) ON DELETE RESTRICT,
				state text NOT NULL CHECK (state IN ('reserved','sent','committed','released','unknown','conflicted')),
				provider text NOT NULL DEFAULT '',
				provider_activation_id text NOT NULL DEFAULT '',
				activation_id bigint UNIQUE REFERENCES activations(id) ON DELETE RESTRICT,
				failure_reason text NOT NULL DEFAULT '',
				cleanup_state text NOT NULL DEFAULT '' CHECK (cleanup_state IN ('','pending','done')),
				cleanup_next_at timestamptz,
				cleanup_lease_owner text NOT NULL DEFAULT '',
				cleanup_lease_until timestamptz,
				cleanup_lease_version bigint NOT NULL DEFAULT 0,
				cleanup_failure_reason text NOT NULL DEFAULT '',
				reserved_at timestamptz NOT NULL DEFAULT now(),
				decided_at timestamptz,
				CHECK (
					(state IN ('reserved','sent') AND activation_id IS NULL AND decided_at IS NULL)
					OR (state='committed' AND activation_id IS NOT NULL
						AND btrim(provider) <> '' AND btrim(provider_activation_id) <> ''
						AND decided_at IS NOT NULL)
					OR (state IN ('released','unknown','conflicted') AND activation_id IS NULL AND decided_at IS NOT NULL)
				),
				CHECK (
					(cleanup_state='' AND cleanup_next_at IS NULL
						AND cleanup_lease_owner='' AND cleanup_lease_until IS NULL)
					OR (cleanup_state='pending' AND state='unknown'
						AND btrim(provider) <> '' AND btrim(provider_activation_id) <> ''
						AND cleanup_next_at IS NOT NULL
						AND ((cleanup_lease_owner='' AND cleanup_lease_until IS NULL)
							OR (btrim(cleanup_lease_owner) <> '' AND cleanup_lease_until IS NOT NULL)))
					OR (cleanup_state='done' AND state='unknown'
						AND btrim(provider) <> '' AND btrim(provider_activation_id) <> ''
						AND cleanup_next_at IS NULL
						AND cleanup_lease_owner='' AND cleanup_lease_until IS NULL)
				)
			)`,
			`CREATE UNIQUE INDEX IF NOT EXISTS batch_purchase_attempts_one_unresolved_idx
				ON batch_purchase_attempts(batch_id) WHERE state IN ('reserved','sent','unknown','conflicted')`,
			`CREATE INDEX IF NOT EXISTS batch_purchase_attempts_batch_idx
				ON batch_purchase_attempts(batch_id, reserved_at DESC)`,
			`CREATE UNIQUE INDEX IF NOT EXISTS batch_purchase_attempts_provider_activation_idx
				ON batch_purchase_attempts(provider, provider_activation_id)
				WHERE btrim(provider) <> '' AND btrim(provider_activation_id) <> ''`,
			`CREATE INDEX IF NOT EXISTS batch_purchase_attempts_cleanup_idx
				ON batch_purchase_attempts(cleanup_next_at, reserved_at)
				WHERE state='unknown' AND cleanup_state='pending'`,
			`INSERT INTO batch_purchase_attempts(
				token, batch_id, state, provider, provider_activation_id,
				activation_id, reserved_at, decided_at
			)
			SELECT 'legacy:' || a.id::text, a.batch_id, 'committed', a.provider,
				a.provider_activation_id, a.id, a.created_at, a.updated_at
			FROM activations a
			ON CONFLICT DO NOTHING`,
			`UPDATE batches b SET
				purchased_count=(SELECT COUNT(*)::integer FROM activations a WHERE a.batch_id=b.id),
				purchase_reserved_count=0,
				purchase_protocol_version=1`,
			// Active rows predate the provider-call reservation protocol. Freeze
			// them during the upgrade; operators can create a fresh protected batch
			// after every old process has stopped.
			`UPDATE activations a SET
				control_action='delete',
				hidden_at=COALESCE(a.hidden_at, now()),
				lease_owner='',
				lease_until=NULL,
				lease_version=a.lease_version+1,
				next_run_at=now(),
				updated_at=now()
			FROM batches b
			WHERE a.batch_id=b.id
				AND b.status IN ('pending','running')
				AND a.finished_at IS NULL`,
			`UPDATE batches SET
				status='failed',
				failure_reason='购买协议升级，旧任务已冻结以避免重复购买',
				finished_at=COALESCE(finished_at, now()),
				updated_at=now()
			WHERE status IN ('pending','running')`,
			`ALTER TABLE batches ADD CONSTRAINT batches_purchase_reserved_max_one_chk
				CHECK (purchase_reserved_count <= 1)`,
			`ALTER TABLE batches ADD CONSTRAINT batches_active_purchase_capacity_chk
				CHECK (status NOT IN ('pending','running') OR purchased_count+purchase_reserved_count <= quantity)`,
			`ALTER TABLE batches ADD CONSTRAINT batches_purchase_protocol_v1_chk
				CHECK (purchase_protocol_version=1)`,
		},
	},
}

// Migrate applies all storage migrations under one transaction-scoped advisory
// lock, so multiple application replicas may safely start at the same time.
func Migrate(ctx context.Context, pool *pgxpool.Pool) error {
	if pool == nil {
		return fmt.Errorf("migrate: nil pool")
	}
	tx, err := pool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return fmt.Errorf("begin migration: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if _, err = tx.Exec(ctx, `SELECT pg_advisory_xact_lock($1)`, int64(0x47504159534d53)); err != nil {
		return fmt.Errorf("lock migrations: %w", err)
	}
	if _, err = tx.Exec(ctx, `CREATE TABLE IF NOT EXISTS schema_migrations (
		version bigint PRIMARY KEY,
		applied_at timestamptz NOT NULL DEFAULT now()
	)`); err != nil {
		return fmt.Errorf("create migration table: %w", err)
	}

	for _, m := range migrations {
		var applied bool
		err = tx.QueryRow(ctx, `SELECT EXISTS (SELECT 1 FROM schema_migrations WHERE version=$1)`, m.version).Scan(&applied)
		if err != nil {
			return fmt.Errorf("read migration %d: %w", m.version, err)
		}
		if applied {
			continue
		}
		for i, statement := range m.statements {
			if _, err = tx.Exec(ctx, statement); err != nil {
				return fmt.Errorf("apply migration %d statement %d: %w", m.version, i+1, err)
			}
		}
		if _, err = tx.Exec(ctx, `INSERT INTO schema_migrations(version) VALUES($1)`, m.version); err != nil {
			return fmt.Errorf("record migration %d: %w", m.version, err)
		}
	}

	if err = tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit migrations: %w", err)
	}
	return nil
}
