package storage

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type migration struct {
	version    int64
	statements []string
	apply      func(context.Context, pgx.Tx, Protector) error
}

const singleActiveBatchIndexName = "batches_single_active_idx"

var migrations = []migration{
	{
		version: 1,
		statements: []string{
			`CREATE TABLE IF NOT EXISTS settings (
				key text PRIMARY KEY,
				value jsonb NOT NULL,
				updated_at timestamptz NOT NULL DEFAULT now()
			)`,
			`CREATE TABLE IF NOT EXISTS batches (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				status text NOT NULL DEFAULT 'pending',
				service_code text NOT NULL,
				service_name text NOT NULL DEFAULT '',
				country_code text NOT NULL,
				country_name text NOT NULL DEFAULT '',
				max_price_amount numeric(18,6) NOT NULL,
				currency text NOT NULL DEFAULT '',
				target_pin_enc bytea NOT NULL DEFAULT ''::bytea,
				config jsonb NOT NULL DEFAULT '{}'::jsonb,
				next_purchase_at timestamptz NOT NULL DEFAULT now(),
				quantity integer NOT NULL CHECK (quantity > 0),
				purchased_count integer NOT NULL DEFAULT 0 CHECK (purchased_count >= 0),
				fulfilled_count integer NOT NULL DEFAULT 0 CHECK (fulfilled_count >= 0),
				inflight_count integer NOT NULL DEFAULT 0 CHECK (inflight_count >= 0),
				failure_reason text NOT NULL DEFAULT '',
				created_at timestamptz NOT NULL DEFAULT now(),
				updated_at timestamptz NOT NULL DEFAULT now(),
				started_at timestamptz,
				finished_at timestamptz,
				CHECK (fulfilled_count <= quantity),
				CHECK (fulfilled_count + inflight_count <= quantity)
			)`,
			`CREATE INDEX IF NOT EXISTS batches_status_created_idx ON batches (status, created_at DESC)`,
			`CREATE TABLE IF NOT EXISTS accounts (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				phone_number text NOT NULL,
				phone_fingerprint char(64) NOT NULL UNIQUE,
				status text NOT NULL,
				balance_rp numeric(24,6),
				credentials_enc bytea NOT NULL DEFAULT ''::bytea,
				target_pin_enc bytea NOT NULL DEFAULT ''::bytea,
				token_state jsonb NOT NULL DEFAULT '{}'::jsonb,
				device_state jsonb NOT NULL DEFAULT '{}'::jsonb,
				metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
				last_login_at timestamptz,
				created_at timestamptz NOT NULL DEFAULT now(),
				updated_at timestamptz NOT NULL DEFAULT now()
			)`,
			`CREATE INDEX IF NOT EXISTS accounts_status_updated_idx ON accounts (status, updated_at DESC)`,
			`CREATE TABLE IF NOT EXISTS activations (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				batch_id bigint NOT NULL REFERENCES batches(id) ON DELETE RESTRICT,
				account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
				provider text NOT NULL,
				provider_activation_id text NOT NULL,
				phone_number text NOT NULL,
				phone_fingerprint char(64) NOT NULL,
				service_code text NOT NULL,
				country_code text NOT NULL,
				operator text NOT NULL DEFAULT '',
				purchase_price_amount numeric(18,6) NOT NULL,
				currency text NOT NULL DEFAULT '',
				status text NOT NULL DEFAULT 'purchased',
				status_changed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
				failure_reason text NOT NULL DEFAULT '',
				balance_rp numeric(24,6),
				balance_checked_at timestamptz,
				ever_fulfilled boolean NOT NULL DEFAULT false,
				slot_reserved boolean NOT NULL DEFAULT false,
				sms_cycle integer NOT NULL DEFAULT 0 CHECK (sms_cycle >= 0),
				next_run_at timestamptz NOT NULL DEFAULT now(),
				lease_owner text NOT NULL DEFAULT '',
				lease_until timestamptz,
				lease_version bigint NOT NULL DEFAULT 0 CHECK (lease_version >= 0),
				control_action text NOT NULL DEFAULT '',
				provider_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
				provider_expires_at timestamptz,
				last_polled_at timestamptz,
				hidden_at timestamptz,
				created_at timestamptz NOT NULL DEFAULT now(),
				updated_at timestamptz NOT NULL DEFAULT now(),
				finished_at timestamptz,
				UNIQUE (provider, provider_activation_id)
			)`,
			`CREATE INDEX IF NOT EXISTS activations_batch_created_idx ON activations (batch_id, created_at DESC)`,
			`CREATE INDEX IF NOT EXISTS activations_visible_idx ON activations (created_at DESC) WHERE hidden_at IS NULL`,
			`CREATE INDEX IF NOT EXISTS activations_runnable_idx ON activations (next_run_at, lease_until) WHERE finished_at IS NULL`,
			`CREATE INDEX IF NOT EXISTS activations_phone_idx ON activations (phone_fingerprint)`,
			`CREATE TABLE IF NOT EXISTS phone_history (
				phone_fingerprint char(64) PRIMARY KEY,
				phone_number text NOT NULL,
				first_activation_id bigint NOT NULL REFERENCES activations(id) ON DELETE RESTRICT,
				last_activation_id bigint NOT NULL REFERENCES activations(id) ON DELETE RESTRICT,
				times_seen integer NOT NULL DEFAULT 1 CHECK (times_seen > 0),
				first_seen_at timestamptz NOT NULL DEFAULT now(),
				last_seen_at timestamptz NOT NULL DEFAULT now()
			)`,
			`CREATE INDEX IF NOT EXISTS phone_history_last_seen_idx ON phone_history (last_seen_at DESC)`,
			`CREATE TABLE IF NOT EXISTS verification_codes (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				activation_id bigint NOT NULL REFERENCES activations(id) ON DELETE RESTRICT,
				cycle_no integer NOT NULL CHECK (cycle_no >= 0),
				phase text NOT NULL,
				ordinal integer NOT NULL CHECK (ordinal >= 0),
				code text NOT NULL,
				provider_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
				provider_received_at timestamptz,
				created_at timestamptz NOT NULL DEFAULT now(),
				UNIQUE (activation_id, cycle_no)
			)`,
			`CREATE INDEX IF NOT EXISTS verification_codes_activation_idx ON verification_codes (activation_id, cycle_no, id)`,
			`CREATE UNIQUE INDEX IF NOT EXISTS verification_codes_subsequent_ordinal_idx
				ON verification_codes (activation_id, ordinal) WHERE phase='subsequent'`,
		},
	},
	{
		version: 2,
		statements: []string{
			`ALTER TABLE batches ADD COLUMN IF NOT EXISTS target_pin_enc bytea NOT NULL DEFAULT ''::bytea`,
			`ALTER TABLE batches ADD COLUMN IF NOT EXISTS next_purchase_at timestamptz NOT NULL DEFAULT now()`,
			`ALTER TABLE activations ADD COLUMN IF NOT EXISTS slot_reserved boolean NOT NULL DEFAULT false`,
			`ALTER TABLE activations ADD COLUMN IF NOT EXISTS lease_version bigint NOT NULL DEFAULT 0`,
		},
	},
	{
		version: 3,
		statements: []string{
			`ALTER TABLE batches ADD COLUMN IF NOT EXISTS purchased_count integer NOT NULL DEFAULT 0 CHECK (purchased_count >= 0)`,
			`UPDATE batches b SET purchased_count=(
				SELECT COUNT(*)::integer FROM activations a WHERE a.batch_id=b.id
			)`,
		},
	},
	{
		version: 4,
		statements: []string{
			// Block concurrent inserts while historical active rows are
			// reconciled and the cross-process uniqueness guard is installed.
			`LOCK TABLE batches IN SHARE ROW EXCLUSIVE MODE`,
			`WITH stale_batches AS (
				SELECT id FROM (
					SELECT id, row_number() OVER (ORDER BY created_at DESC, id DESC) AS active_rank
					FROM batches
					WHERE status IN ('pending','running')
				) ranked
				WHERE active_rank > 1
			)
			UPDATE activations a SET
				control_action='delete',
				hidden_at=COALESCE(a.hidden_at, now()),
				lease_owner='',
				lease_until=NULL,
				lease_version=a.lease_version+1,
				next_run_at=now(),
				updated_at=now()
			FROM stale_batches s
			WHERE a.batch_id=s.id AND a.finished_at IS NULL`,
			`WITH stale_batches AS (
				SELECT id FROM (
					SELECT id, row_number() OVER (ORDER BY created_at DESC, id DESC) AS active_rank
					FROM batches
					WHERE status IN ('pending','running')
				) ranked
				WHERE active_rank > 1
			)
			UPDATE batches b SET
				status='cancelled',
				finished_at=COALESCE(b.finished_at, now()),
				updated_at=now()
			FROM stale_batches s
			WHERE b.id=s.id`,
			`CREATE UNIQUE INDEX IF NOT EXISTS ` + singleActiveBatchIndexName + `
				ON batches ((true)) WHERE status IN ('pending','running')`,
		},
	},
	{
		version: 5,
		statements: []string{
			`ALTER TABLE batches ADD COLUMN IF NOT EXISTS purchase_reserved_count integer NOT NULL DEFAULT 0 CHECK (purchase_reserved_count >= 0)`,
			// New writers explicitly insert protocol version one. Keeping zero as
			// the database default prevents an older binary from starting another
			// unprotected batch after this migration is installed.
			`ALTER TABLE batches ADD COLUMN IF NOT EXISTS purchase_protocol_version integer NOT NULL DEFAULT 0`,
			`CREATE TABLE IF NOT EXISTS batch_purchase_attempts (
				token text PRIMARY KEY CHECK (btrim(token) <> ''),
				batch_id bigint NOT NULL REFERENCES batches(id) ON DELETE RESTRICT,
				state text NOT NULL CHECK (state IN ('reserved','sent','committed','released','unknown','conflicted')),
				provider text NOT NULL DEFAULT '',
				provider_activation_id text NOT NULL DEFAULT '',
				activation_id bigint UNIQUE REFERENCES activations(id) ON DELETE RESTRICT,
				failure_reason text NOT NULL DEFAULT '',
				cleanup_state text NOT NULL DEFAULT '' CHECK (cleanup_state IN ('','pending','done')),
				cleanup_next_at timestamptz,
				cleanup_lease_owner text NOT NULL DEFAULT '',
				cleanup_lease_until timestamptz,
				cleanup_lease_version bigint NOT NULL DEFAULT 0,
				cleanup_failure_reason text NOT NULL DEFAULT '',
				reserved_at timestamptz NOT NULL DEFAULT now(),
				decided_at timestamptz,
				CHECK (
					(state IN ('reserved','sent') AND activation_id IS NULL AND decided_at IS NULL)
					OR (state='committed' AND activation_id IS NOT NULL
						AND btrim(provider) <> '' AND btrim(provider_activation_id) <> ''
						AND decided_at IS NOT NULL)
					OR (state IN ('released','unknown','conflicted') AND activation_id IS NULL AND decided_at IS NOT NULL)
				),
				CHECK (
					(cleanup_state='' AND cleanup_next_at IS NULL
						AND cleanup_lease_owner='' AND cleanup_lease_until IS NULL)
					OR (cleanup_state='pending' AND state='unknown'
						AND btrim(provider) <> '' AND btrim(provider_activation_id) <> ''
						AND cleanup_next_at IS NOT NULL
						AND ((cleanup_lease_owner='' AND cleanup_lease_until IS NULL)
							OR (btrim(cleanup_lease_owner) <> '' AND cleanup_lease_until IS NOT NULL)))
					OR (cleanup_state='done' AND state='unknown'
						AND btrim(provider) <> '' AND btrim(provider_activation_id) <> ''
						AND cleanup_next_at IS NULL
						AND cleanup_lease_owner='' AND cleanup_lease_until IS NULL)
				)
			)`,
			`CREATE UNIQUE INDEX IF NOT EXISTS batch_purchase_attempts_one_unresolved_idx
				ON batch_purchase_attempts(batch_id) WHERE state IN ('reserved','sent','unknown','conflicted')`,
			`CREATE INDEX IF NOT EXISTS batch_purchase_attempts_batch_idx
				ON batch_purchase_attempts(batch_id, reserved_at DESC)`,
			`CREATE UNIQUE INDEX IF NOT EXISTS batch_purchase_attempts_provider_activation_idx
				ON batch_purchase_attempts(provider, provider_activation_id)
				WHERE btrim(provider) <> '' AND btrim(provider_activation_id) <> ''`,
			`CREATE INDEX IF NOT EXISTS batch_purchase_attempts_cleanup_idx
				ON batch_purchase_attempts(cleanup_next_at, reserved_at)
				WHERE state='unknown' AND cleanup_state='pending'`,
			`INSERT INTO batch_purchase_attempts(
				token, batch_id, state, provider, provider_activation_id,
				activation_id, reserved_at, decided_at
			)
			SELECT 'legacy:' || a.id::text, a.batch_id, 'committed', a.provider,
				a.provider_activation_id, a.id, a.created_at, a.updated_at
			FROM activations a
			ON CONFLICT DO NOTHING`,
			`UPDATE batches b SET
				purchased_count=(SELECT COUNT(*)::integer FROM activations a WHERE a.batch_id=b.id),
				purchase_reserved_count=0,
				purchase_protocol_version=1`,
			// Active rows predate the provider-call reservation protocol. Freeze
			// them during the upgrade; operators can create a fresh protected batch
			// after every old process has stopped.
			`UPDATE activations a SET
				control_action='delete',
				hidden_at=COALESCE(a.hidden_at, now()),
				lease_owner='',
				lease_until=NULL,
				lease_version=a.lease_version+1,
				next_run_at=now(),
				updated_at=now()
			FROM batches b
			WHERE a.batch_id=b.id
				AND b.status IN ('pending','running')
				AND a.finished_at IS NULL`,
			`UPDATE batches SET
				status='failed',
				failure_reason='购买协议升级，旧任务已冻结以避免重复购买',
				finished_at=COALESCE(finished_at, now()),
				updated_at=now()
			WHERE status IN ('pending','running')`,
			`ALTER TABLE batches ADD CONSTRAINT batches_purchase_reserved_max_one_chk
				CHECK (purchase_reserved_count <= 1)`,
			`ALTER TABLE batches ADD CONSTRAINT batches_active_purchase_capacity_chk
				CHECK (status NOT IN ('pending','running') OR purchased_count+purchase_reserved_count <= quantity)`,
			`ALTER TABLE batches ADD CONSTRAINT batches_purchase_protocol_v1_chk
				CHECK (purchase_protocol_version=1)`,
		},
	},
	{
		version: 6,
		statements: []string{
			`ALTER TABLE activations ADD COLUMN IF NOT EXISTS status_changed_at timestamptz NOT NULL DEFAULT clock_timestamp()`,
		},
	},
	{
		version: 7,
		statements: []string{
			// Converge batches whose last unsuccessful activation was finalized by
			// an older release. Their counters already prove that every planned
			// purchase has finished without one fulfilled number.
			`UPDATE batches SET
				status='failed',
				failure_reason='` + allPurchasedActivationsFailedReason + `',
				finished_at=COALESCE(finished_at, now()),
				updated_at=now()
			WHERE status IN ('pending','running')
				AND purchased_count >= quantity
				AND purchase_reserved_count=0
				AND fulfilled_count=0
				AND inflight_count=0`,
		},
	},
	{
		version: 8,
		statements: []string{
			// Older workers overwrote the durable unregistered classification
			// while retrying HeroSMS finalization. Match only that complete legacy
			// error shape, while accepting the old SMSBower and new HeroSMS labels.
			`UPDATE activations SET
				failure_reason='未注册',
				updated_at=now()
			WHERE status='unregistered'
				AND failure_reason ~* '^[[:space:]]*(smsbower|herosms)[[:space:]]+setstatus[[:space:]]*:[[:space:]]*http_409[[:space:]]*:[[:space:]]*conflict[[:space:]]*$'`,
		},
	},
	{
		version: 9,
		statements: []string{
			// Quantity is the successful-activation target. Provider allocations
			// that later fail release an inflight slot and may be replaced, so the
			// lifetime purchased_count is intentionally not capacity constrained.
			`ALTER TABLE batches DROP CONSTRAINT IF EXISTS batches_active_purchase_capacity_chk`,
			`ALTER TABLE batches ADD CONSTRAINT batches_success_slot_capacity_chk
				CHECK (fulfilled_count+inflight_count+purchase_reserved_count <= quantity)`,
			`DROP TABLE IF EXISTS phone_history`,
		},
	},
	{
		version: 10,
		statements: []string{
			// A callback can race the provider-purchase transaction. Keeping the
			// activation foreign key nullable lets the inbox commit first; purchase
			// persistence and event claiming both attach these early callbacks later.
			`ALTER TABLE activations ADD COLUMN IF NOT EXISTS webhook_wakeup_at timestamptz`,
			// PostgreSQL json (unlike jsonb) retains the original token order and
			// whitespace, so the exact authenticated request remains auditable.
			`CREATE TABLE IF NOT EXISTS hero_sms_webhook_events (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				activation_id bigint REFERENCES activations(id) ON DELETE SET NULL,
				provider_activation_id text NOT NULL CHECK (btrim(provider_activation_id) <> ''),
				code text,
				message_text text,
				phone_number text NOT NULL DEFAULT '',
				service_code text NOT NULL DEFAULT '',
				country_code text NOT NULL DEFAULT '',
				provider_received_at timestamptz,
				raw_payload json NOT NULL,
				payload_fingerprint char(64) NOT NULL UNIQUE,
				status text NOT NULL DEFAULT 'received'
					CHECK (status IN ('received','processing','processed','ignored')),
				attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
				last_error text NOT NULL DEFAULT '',
				next_attempt_at timestamptz NOT NULL DEFAULT now(),
				claimed_lease_owner text NOT NULL DEFAULT '',
				claimed_lease_version bigint NOT NULL DEFAULT 0 CHECK (claimed_lease_version >= 0),
				received_at timestamptz NOT NULL DEFAULT now(),
				processed_at timestamptz,
				CHECK (
					(status='received' AND claimed_lease_owner='' AND claimed_lease_version=0 AND processed_at IS NULL)
					OR (status='processing' AND btrim(claimed_lease_owner) <> '' AND claimed_lease_version > 0 AND processed_at IS NULL)
					OR (status='processed' AND btrim(claimed_lease_owner) <> '' AND claimed_lease_version > 0 AND processed_at IS NOT NULL)
					OR (status='ignored' AND processed_at IS NOT NULL
						AND ((claimed_lease_owner='' AND claimed_lease_version=0)
							OR (btrim(claimed_lease_owner) <> '' AND claimed_lease_version > 0)))
				)
			)`,
			`CREATE INDEX IF NOT EXISTS hero_sms_webhook_events_activation_claim_idx
				ON hero_sms_webhook_events(activation_id, status, next_attempt_at, received_at, id)
				WHERE status IN ('received','processing')`,
			`CREATE INDEX IF NOT EXISTS hero_sms_webhook_events_processing_idx
				ON hero_sms_webhook_events(activation_id)
				WHERE status='processing'`,
			`CREATE INDEX IF NOT EXISTS hero_sms_webhook_events_unattached_idx
				ON hero_sms_webhook_events(provider_activation_id, received_at, id)
				WHERE activation_id IS NULL`,
		},
	},
	{
		version: 11,
		statements: []string{
			// Every row is one independently scheduled number slot. submission_id
			// groups no runtime work; this header only makes create retries idempotent.
			`CREATE TABLE IF NOT EXISTS hero_sms_task_submissions (
				id text PRIMARY KEY CHECK (btrim(id) <> ''),
				request_fingerprint char(64) NOT NULL,
				quantity integer NOT NULL CHECK (quantity > 0),
				created_at timestamptz NOT NULL DEFAULT now()
			)`,
			`CREATE TABLE IF NOT EXISTS hero_sms_number_tasks (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				submission_id text NOT NULL REFERENCES hero_sms_task_submissions(id) ON DELETE RESTRICT,
				status text NOT NULL DEFAULT 'waiting_number'
					CHECK (status IN ('waiting_number','purchasing','active','purchase_unknown','settling','stopped','refunded','settled','expired')),
				product_kind text NOT NULL CHECK (product_kind IN ('activation','rent')),
				service_code text NOT NULL CHECK (btrim(service_code) <> ''),
				service_name text NOT NULL DEFAULT '',
				country_code text NOT NULL CHECK (btrim(country_code) <> ''),
				country_name text NOT NULL DEFAULT '',
				verification_type text NOT NULL CHECK (btrim(verification_type) <> ''),
				duration_hours integer CHECK (duration_hours > 0),
				max_price_amount numeric(18,6),
				provider text NOT NULL DEFAULT 'hero-sms',
				purchase_token text NOT NULL DEFAULT '',
				provider_activation_id text,
				phone_number text NOT NULL DEFAULT '',
				operator text NOT NULL DEFAULT '',
				activation_cost numeric(18,6),
				currency text NOT NULL DEFAULT '',
				purchased_at timestamptz,
				expires_at timestamptz,
				refundable_until timestamptz,
				refund_status text NOT NULL DEFAULT ''
					CHECK (refund_status IN ('','refundable','requested','refunded','unavailable','settled')),
				message_count integer NOT NULL DEFAULT 0 CHECK (message_count >= 0),
				continuation_count integer NOT NULL DEFAULT 0 CHECK (continuation_count >= 0),
				first_message_at timestamptz,
				next_run_at timestamptz NOT NULL DEFAULT now(),
				lease_owner text NOT NULL DEFAULT '',
				lease_until timestamptz,
				lease_version bigint NOT NULL DEFAULT 0 CHECK (lease_version >= 0),
				stop_requested boolean NOT NULL DEFAULT false,
				retry_count integer NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
				last_error text NOT NULL DEFAULT '',
				last_polled_at timestamptz,
				webhook_wakeup_at timestamptz,
				provider_payload json NOT NULL DEFAULT '{}'::json,
				created_at timestamptz NOT NULL DEFAULT now(),
				updated_at timestamptz NOT NULL DEFAULT now(),
				finished_at timestamptz,
				CHECK ((product_kind='activation' AND duration_hours IS NULL)
					OR (product_kind='rent' AND duration_hours IS NOT NULL)),
				CHECK ((lease_owner='' AND lease_until IS NULL)
					OR (btrim(lease_owner) <> '' AND lease_until IS NOT NULL)),
				CHECK (status<>'purchasing' OR btrim(purchase_token) <> ''),
				CONSTRAINT hero_sms_number_tasks_continuation_count_lte_chk
					CHECK (continuation_count <= message_count)
			)`,
			`CREATE UNIQUE INDEX IF NOT EXISTS hero_sms_number_tasks_provider_activation_idx
				ON hero_sms_number_tasks(provider, provider_activation_id)
				WHERE provider_activation_id IS NOT NULL`,
			`CREATE UNIQUE INDEX IF NOT EXISTS hero_sms_number_tasks_purchase_token_idx
				ON hero_sms_number_tasks(purchase_token) WHERE btrim(purchase_token) <> ''`,
			`CREATE INDEX IF NOT EXISTS hero_sms_number_tasks_list_idx
				ON hero_sms_number_tasks(created_at DESC, id DESC)`,
			`CREATE INDEX IF NOT EXISTS hero_sms_number_tasks_runnable_idx
				ON hero_sms_number_tasks(next_run_at, lease_until, id) WHERE finished_at IS NULL`,
			// The message audit log is append-only. task_id remains nullable for a
			// callback which commits before the matching number purchase does.
			`CREATE TABLE IF NOT EXISTS hero_sms_number_messages (
				id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				task_id bigint REFERENCES hero_sms_number_tasks(id) ON DELETE SET NULL,
				provider_activation_id text NOT NULL CHECK (btrim(provider_activation_id) <> ''),
				provider_message_id text NOT NULL DEFAULT '',
				source text NOT NULL CHECK (source IN ('webhook','poll')),
				code text NOT NULL DEFAULT '',
				message_text text NOT NULL DEFAULT '',
				provider_received_at timestamptz,
				raw_payload json NOT NULL,
				payload_fingerprint char(64) NOT NULL UNIQUE,
				created_at timestamptz NOT NULL DEFAULT now(),
				CHECK (btrim(code) <> '' OR btrim(message_text) <> '')
			)`,
			`CREATE INDEX IF NOT EXISTS hero_sms_number_messages_task_idx
				ON hero_sms_number_messages(task_id, provider_received_at, created_at, id)`,
			`CREATE UNIQUE INDEX IF NOT EXISTS hero_sms_number_messages_provider_id_idx
				ON hero_sms_number_messages(provider_activation_id, provider_message_id)
				WHERE btrim(provider_message_id) <> ''`,
			`CREATE INDEX IF NOT EXISTS hero_sms_number_messages_orphan_idx
				ON hero_sms_number_messages(provider_activation_id, created_at, id)
				WHERE task_id IS NULL`,
		},
	},
	{
		version: 12,
		statements: []string{
			// Compatibility for development databases which applied the first v11
			// draft before durable activation continuation was introduced.
			`ALTER TABLE hero_sms_number_tasks ADD COLUMN IF NOT EXISTS
				continuation_count integer NOT NULL DEFAULT 0 CHECK (continuation_count >= 0)`,
			// An intermediate draft exposed the counter before installing its upper
			// bound. Converge any such rows before validating the durable invariant.
			`UPDATE hero_sms_number_tasks SET
				continuation_count=GREATEST(0, LEAST(COALESCE(continuation_count, 0), message_count))
			WHERE continuation_count IS NULL
				OR continuation_count < 0
				OR continuation_count > message_count`,
			`ALTER TABLE hero_sms_number_tasks
				ALTER COLUMN continuation_count SET DEFAULT 0`,
			`ALTER TABLE hero_sms_number_tasks
				ALTER COLUMN continuation_count SET NOT NULL`,
			`DO $$ BEGIN
				IF NOT EXISTS (
					SELECT 1 FROM pg_constraint
					WHERE conname='hero_sms_number_tasks_continuation_count_nonnegative_chk'
						AND conrelid='hero_sms_number_tasks'::regclass
				) THEN
					ALTER TABLE hero_sms_number_tasks
						ADD CONSTRAINT hero_sms_number_tasks_continuation_count_nonnegative_chk
						CHECK (continuation_count >= 0) NOT VALID;
				END IF;
			END $$`,
			`ALTER TABLE hero_sms_number_tasks
				VALIDATE CONSTRAINT hero_sms_number_tasks_continuation_count_nonnegative_chk`,
			`DO $$ BEGIN
				IF NOT EXISTS (
					SELECT 1 FROM pg_constraint
					WHERE conname='hero_sms_number_tasks_continuation_count_lte_chk'
						AND conrelid='hero_sms_number_tasks'::regclass
				) THEN
					ALTER TABLE hero_sms_number_tasks
						ADD CONSTRAINT hero_sms_number_tasks_continuation_count_lte_chk
						CHECK (continuation_count <= message_count) NOT VALID;
				END IF;
			END $$`,
			`ALTER TABLE hero_sms_number_tasks
				VALIDATE CONSTRAINT hero_sms_number_tasks_continuation_count_lte_chk`,
			// Early message drafts did not guard the provider message identity. Keep
			// every audit row, but clear the duplicate identity on all but the oldest
			// row so the partial unique index can be installed without data loss.
			`WITH duplicate_provider_messages AS (
				SELECT id FROM (
					SELECT id, row_number() OVER (
						PARTITION BY provider_activation_id, provider_message_id
						ORDER BY created_at ASC, id ASC
					) AS duplicate_rank
					FROM hero_sms_number_messages
					WHERE btrim(provider_message_id) <> ''
				) ranked
				WHERE duplicate_rank > 1
			)
			UPDATE hero_sms_number_messages AS message SET
				provider_message_id=''
			FROM duplicate_provider_messages AS duplicate
			WHERE message.id=duplicate.id`,
			`CREATE UNIQUE INDEX IF NOT EXISTS hero_sms_number_messages_provider_id_idx
				ON hero_sms_number_messages(provider_activation_id, provider_message_id)
				WHERE btrim(provider_message_id) <> ''`,
		},
	},
	{
		version: 13,
		statements: []string{
			`CREATE TABLE IF NOT EXISTS storage_encryption_state (
				id smallint PRIMARY KEY CHECK (id=1),
				key_check bytea NOT NULL CHECK (octet_length(key_check)>0)
			)`,
			`ALTER TABLE accounts ADD COLUMN IF NOT EXISTS
				sensitive_enc bytea NOT NULL DEFAULT ''::bytea`,
			`ALTER TABLE activations ADD COLUMN IF NOT EXISTS
				sensitive_enc bytea NOT NULL DEFAULT ''::bytea`,
			`ALTER TABLE verification_codes ADD COLUMN IF NOT EXISTS
				sensitive_enc bytea NOT NULL DEFAULT ''::bytea`,
			`ALTER TABLE hero_sms_webhook_events ADD COLUMN IF NOT EXISTS
				sensitive_enc bytea NOT NULL DEFAULT ''::bytea`,
		},
		apply: migrateLegacySensitiveData,
	},
	{
		version: 14,
		statements: []string{
			`ALTER TABLE accounts ADD CONSTRAINT accounts_sensitive_ciphertext_chk
				CHECK (octet_length(sensitive_enc)>0 AND phone_number='')`,
			`ALTER TABLE activations ADD CONSTRAINT activations_sensitive_ciphertext_chk
				CHECK (octet_length(sensitive_enc)>0 AND phone_number='' AND provider_payload='{}'::jsonb)`,
			`ALTER TABLE verification_codes ADD CONSTRAINT verification_codes_sensitive_ciphertext_chk
				CHECK (octet_length(sensitive_enc)>0 AND code='' AND provider_payload='{}'::jsonb)`,
			`ALTER TABLE hero_sms_webhook_events ADD CONSTRAINT hero_sms_webhook_events_sensitive_ciphertext_chk
				CHECK (octet_length(sensitive_enc)>0 AND code IS NULL AND message_text IS NULL
					AND phone_number='' AND raw_payload::jsonb='{}'::jsonb)`,
		},
	},
	{
		version: 15,
		statements: []string{
			`ALTER TABLE hero_sms_number_tasks ADD COLUMN IF NOT EXISTS
				continuation_pending_count integer NOT NULL DEFAULT 0`,
			`ALTER TABLE hero_sms_number_tasks ADD COLUMN IF NOT EXISTS
				supports_continuation boolean NOT NULL DEFAULT false`,
			`UPDATE hero_sms_number_tasks SET supports_continuation=false
			WHERE supports_continuation IS NULL`,
			`UPDATE hero_sms_number_tasks SET supports_continuation=true
			WHERE product_kind='activation' AND verification_type='sms'
				AND (
					provider_payload::jsonb -> 'canGetAnotherSms' = 'true'::jsonb
					OR provider_payload::jsonb -> 'can_get_another_sms' = 'true'::jsonb
				)`,
			// An interrupted development migration may have exposed a nullable or
			// invalid pending target. Clear only targets which cannot represent an
			// in-flight activation continuation before validating the invariant.
			`UPDATE hero_sms_number_tasks SET continuation_pending_count=0
			WHERE continuation_pending_count IS NULL
				OR continuation_pending_count < 0
				OR (continuation_pending_count<>0 AND NOT (
					status='active'
					AND product_kind='activation'
					AND supports_continuation=true
					AND continuation_count < continuation_pending_count
					AND continuation_pending_count <= message_count
				))`,
			`ALTER TABLE hero_sms_number_tasks
				ALTER COLUMN continuation_pending_count SET DEFAULT 0`,
			`ALTER TABLE hero_sms_number_tasks
				ALTER COLUMN continuation_pending_count SET NOT NULL`,
			`ALTER TABLE hero_sms_number_tasks
				ALTER COLUMN supports_continuation SET DEFAULT false`,
			`ALTER TABLE hero_sms_number_tasks
				ALTER COLUMN supports_continuation SET NOT NULL`,
			`DO $$ BEGIN
				IF NOT EXISTS (
					SELECT 1 FROM pg_constraint
					WHERE conname='hero_sms_number_tasks_continuation_pending_state_chk'
						AND conrelid='hero_sms_number_tasks'::regclass
				) THEN
					ALTER TABLE hero_sms_number_tasks
						ADD CONSTRAINT hero_sms_number_tasks_continuation_pending_state_chk
						CHECK (continuation_pending_count=0 OR (
							status='active'
							AND product_kind='activation'
							AND supports_continuation=true
							AND continuation_count < continuation_pending_count
							AND continuation_pending_count <= message_count
						)) NOT VALID;
				END IF;
			END $$`,
			`ALTER TABLE hero_sms_number_tasks
				VALIDATE CONSTRAINT hero_sms_number_tasks_continuation_pending_state_chk`,
		},
	},
	{
		version: 16,
		statements: []string{
			// v9 removed the historical clear-text phone table. Repeat this as a
			// drift guard before replacing the remaining deterministic digests.
			`DROP TABLE IF EXISTS phone_history`,
		},
		apply: migrateSensitiveBlindIndexes,
	},
}

// Migrate applies all storage migrations under one transaction-scoped advisory
// lock, so multiple application replicas may safely start at the same time.
func Migrate(ctx context.Context, pool *pgxpool.Pool, protector Protector) error {
	if pool == nil {
		return fmt.Errorf("migrate: nil pool")
	}
	if protector == nil {
		return fmt.Errorf("migrate: nil sensitive-data protector")
	}
	if _, ok := protector.(BlindIndexer); !ok {
		return fmt.Errorf("migrate: sensitive-data protector does not support blind indexes")
	}
	tx, err := pool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return fmt.Errorf("begin migration: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if _, err = tx.Exec(ctx, `SELECT pg_advisory_xact_lock($1)`, int64(0x47504159534d53)); err != nil {
		return fmt.Errorf("lock migrations: %w", err)
	}
	if _, err = tx.Exec(ctx, `CREATE TABLE IF NOT EXISTS schema_migrations (
		version bigint PRIMARY KEY,
		applied_at timestamptz NOT NULL DEFAULT now()
	)`); err != nil {
		return fmt.Errorf("create migration table: %w", err)
	}

	for _, m := range migrations {
		var applied bool
		err = tx.QueryRow(ctx, `SELECT EXISTS (SELECT 1 FROM schema_migrations WHERE version=$1)`, m.version).Scan(&applied)
		if err != nil {
			return fmt.Errorf("read migration %d: %w", m.version, err)
		}
		if applied {
			continue
		}
		for i, statement := range m.statements {
			if _, err = tx.Exec(ctx, statement); err != nil {
				return fmt.Errorf("apply migration %d statement %d: %w", m.version, i+1, err)
			}
		}
		if m.apply != nil {
			if err = m.apply(ctx, tx, protector); err != nil {
				return fmt.Errorf("apply migration %d data hook: %w", m.version, err)
			}
		}
		if _, err = tx.Exec(ctx, `INSERT INTO schema_migrations(version) VALUES($1)`, m.version); err != nil {
			return fmt.Errorf("record migration %d: %w", m.version, err)
		}
	}
	if err = verifyStorageProtector(ctx, tx, protector); err != nil {
		return fmt.Errorf("verify storage encryption: %w", err)
	}

	if err = tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit migrations: %w", err)
	}
	return nil
}
